### ISSUE TITLE
Redirect to a directory

### ISSUE THREAD

**Issue by wessven** [bryanwweber/pelican-redirect#2]
When migrating from a different site, one might have a URL such as https://example.com/articles/my-article.

Currently, if one specifies the URL to redirect from /articles/my-article, it will create an extensionless HTML file. The web server might not be able to recognise it as an HTML file, and would need to be configured to do so. This can be a pain.

My proposal is to detect whether a redirect has an extension or not. If it does not have one, then create a directory named "my-article", and generate the redirecting HTML file inside of it as index.html.

**Comment by bryanwweber** [comment]
Hi! Thanks for reporting this. I agree it's an important case 😊 what about just adding the `index.html` into the end of your string, like `https://example.com/articles/my-article/index.html`? I hope I didn't misunderstand the question ☺️

**Comment by wessven** [comment]
Hey, first off, thanks for writing this plugin; it makes migrating existing blogs much easier. I'm still evaluating Pelican, but because I'm more comfortable with Python than Ruby or Go, it's a strong contender for me.

You make a valid point. It think having the plugin generate the index.html for you is just more intuitive (and one less thing for the content creator to worry about).

**Comment by bryanwweber** [comment]
I'm glad it's helpful! I think it makes sense to go along with other similar software, so I left a few comments on the PR 😄
